=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'aspose_storage_cloud'

# Common files
require_relative 'aspose_platform_cloud/api_client'
require_relative 'aspose_platform_cloud/api_error'
require_relative 'aspose_platform_cloud/version'
require_relative 'aspose_platform_cloud/aspose_app'
require_relative 'aspose_platform_cloud/configuration'

# Models
require_relative 'aspose_platform_cloud/models/app'
require_relative 'aspose_platform_cloud/models/app_usage'
require_relative 'aspose_platform_cloud/models/disc_usage'
require_relative 'aspose_platform_cloud/models/file'
require_relative 'aspose_platform_cloud/models/file_exist'
require_relative 'aspose_platform_cloud/models/file_response'
require_relative 'aspose_platform_cloud/models/folder_response'
require_relative 'aspose_platform_cloud/models/heroku_request'
require_relative 'aspose_platform_cloud/models/heroku_request_options'
require_relative 'aspose_platform_cloud/models/saa_spose_response'
require_relative 'aspose_platform_cloud/models/user_usage_summary_statistics'
require_relative 'aspose_platform_cloud/models/application_usage_response'
require_relative 'aspose_platform_cloud/models/disc_usage_response'
require_relative 'aspose_platform_cloud/models/file_exist_response'
require_relative 'aspose_platform_cloud/models/file_version'
require_relative 'aspose_platform_cloud/models/file_versions_response'
require_relative 'aspose_platform_cloud/models/move_file_response'
require_relative 'aspose_platform_cloud/models/move_folder_response'
require_relative 'aspose_platform_cloud/models/remove_file_response'
require_relative 'aspose_platform_cloud/models/remove_folder_response'
require_relative 'aspose_platform_cloud/models/storage_exist_response'
require_relative 'aspose_platform_cloud/models/user_usage_summary_response'
require_relative 'aspose_platform_cloud/models/access_token_response'

# APIs
require_relative 'aspose_platform_cloud/api/app_api'
require_relative 'aspose_platform_cloud/api/app_statistics_api'
require_relative 'aspose_platform_cloud/api/file_api'
require_relative 'aspose_platform_cloud/api/folder_api'
require_relative 'aspose_platform_cloud/api/heroku_api'
require_relative 'aspose_platform_cloud/api/storage_api'
require_relative 'aspose_platform_cloud/api/usage_api'
require_relative 'aspose_platform_cloud/api/o_auth_api'

module AsposePlatformCloud
  class << self
    # Customize default settings for the SDK using block.
    #   AsposePlatformCloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
