=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module AsposePlatformCloud

  class UserUsageSummaryStatistics
    attr_accessor :documents_used

    attr_accessor :documents_limit

    attr_accessor :barcodes_used

    attr_accessor :barcodes_limit

    attr_accessor :ocrs_used

    attr_accessor :ocrs_limit

    attr_accessor :calls_used

    attr_accessor :calls_limit


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'documents_used' => :'DocumentsUsed',
        :'documents_limit' => :'DocumentsLimit',
        :'barcodes_used' => :'BarcodesUsed',
        :'barcodes_limit' => :'BarcodesLimit',
        :'ocrs_used' => :'OcrsUsed',
        :'ocrs_limit' => :'OcrsLimit',
        :'calls_used' => :'CallsUsed',
        :'calls_limit' => :'CallsLimit'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'documents_used' => :'Integer',
        :'documents_limit' => :'Integer',
        :'barcodes_used' => :'Integer',
        :'barcodes_limit' => :'Integer',
        :'ocrs_used' => :'Integer',
        :'ocrs_limit' => :'Integer',
        :'calls_used' => :'Integer',
        :'calls_limit' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'DocumentsUsed')
        self.documents_used = attributes[:'DocumentsUsed']
      end

      if attributes.has_key?(:'DocumentsLimit')
        self.documents_limit = attributes[:'DocumentsLimit']
      end

      if attributes.has_key?(:'BarcodesUsed')
        self.barcodes_used = attributes[:'BarcodesUsed']
      end

      if attributes.has_key?(:'BarcodesLimit')
        self.barcodes_limit = attributes[:'BarcodesLimit']
      end

      if attributes.has_key?(:'OcrsUsed')
        self.ocrs_used = attributes[:'OcrsUsed']
      end

      if attributes.has_key?(:'OcrsLimit')
        self.ocrs_limit = attributes[:'OcrsLimit']
      end

      if attributes.has_key?(:'CallsUsed')
        self.calls_used = attributes[:'CallsUsed']
      end

      if attributes.has_key?(:'CallsLimit')
        self.calls_limit = attributes[:'CallsLimit']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @documents_used.nil?
        invalid_properties.push("invalid value for 'documents_used', documents_used cannot be nil.")
      end

      if @documents_limit.nil?
        invalid_properties.push("invalid value for 'documents_limit', documents_limit cannot be nil.")
      end

      if @barcodes_used.nil?
        invalid_properties.push("invalid value for 'barcodes_used', barcodes_used cannot be nil.")
      end

      if @barcodes_limit.nil?
        invalid_properties.push("invalid value for 'barcodes_limit', barcodes_limit cannot be nil.")
      end

      if @ocrs_used.nil?
        invalid_properties.push("invalid value for 'ocrs_used', ocrs_used cannot be nil.")
      end

      if @ocrs_limit.nil?
        invalid_properties.push("invalid value for 'ocrs_limit', ocrs_limit cannot be nil.")
      end

      if @calls_used.nil?
        invalid_properties.push("invalid value for 'calls_used', calls_used cannot be nil.")
      end

      if @calls_limit.nil?
        invalid_properties.push("invalid value for 'calls_limit', calls_limit cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @documents_used.nil?
      return false if @documents_limit.nil?
      return false if @barcodes_used.nil?
      return false if @barcodes_limit.nil?
      return false if @ocrs_used.nil?
      return false if @ocrs_limit.nil?
      return false if @calls_used.nil?
      return false if @calls_limit.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          documents_used == o.documents_used &&
          documents_limit == o.documents_limit &&
          barcodes_used == o.barcodes_used &&
          barcodes_limit == o.barcodes_limit &&
          ocrs_used == o.ocrs_used &&
          ocrs_limit == o.ocrs_limit &&
          calls_used == o.calls_used &&
          calls_limit == o.calls_limit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [documents_used, documents_limit, barcodes_used, barcodes_limit, ocrs_used, ocrs_limit, calls_used, calls_limit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AsposePlatformCloud.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
